spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://db.mysql.ibn.local/ibn_rms?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  #mybatis mapper配置文件的位置
  mapper-locations: classpath*:mybatis/*Dao.xml